Tree
string Tree::proposition
Referenced by getProposition.
SemanticTableaux Tree::tableaux
Referenced by isTautology, exportProof.
shared_ptr<Node> Tree::tree
Referenced by CNF::CNF, CNF::getDavidPutnam, I_CNF::generateCNF, Predicate::Predicate, Tree, getTree, getProposition, getValue, isTautology, exportGraph.
list<string> Tree::varList
Referenced by CNF::getListVariable, CNF::getDavidPutnam, Predicate::getListVariable, getListVariable, TruthTable::generateTable, TruthTable::getNormalize.
string Tree::prop_in
Referenced by CNF::CNF, CNF::getListVariable, Predicate::Predicate, Predicate::getListVariable, Tree, getListVariable.
shared_ptr< Node > Tree::parse(string prop, unsigned int &pos)
References getNode, getStatement.
Referenced by Tree.
shared_ptr< Node > Tree::getStatement(string prop, unsigned int &pos)
Referenced by parse.
shared_ptr< Node > Tree::getNode(char notation)
Referenced by parse.
Tree::Tree(string prop="")
References prop_in, tree, parse.
Referenced by TruthTable::getNormalize.
Tree::Tree(shared_ptr< Node > tree=nullptr)
References prop_in.
Tree::~Tree()
shared_ptr< Node > Tree::getTree()
References tree.
list< string > Tree::getListVariable()
References varList, prop_in, contains.
Referenced by SimpleTable::getAllRowsGroup, TruthTable::generateTable.
string Tree::getProposition()
References proposition, tree.
bool Tree::isTautology()
References tableaux, tree, SemanticTableaux::isTautology.
bool Tree::getValue(string valList)
References tree.
Referenced by TruthTable::generateTable.
bool Tree::exportGraph(string title, string filenname)
References tree.
bool Tree::exportProof(string title, string filenname)
References tableaux, SemanticTableaux::ExportProof.
string Tree::getDavidPutnam()
get David Putnam
string, showing David Putnam result