I_CNF
string I_CNF::solveNonJanus(shared_ptr< Node > node, char v)
Solve non-janus based on MulitiAnd node and variable v.
node - MultiAnd Node pointer to find janus node - node will be filter out if janus have found v - String represent for current variable String contains founded janus Emplty string if janus not found
Referenced by CNF::getDavidPutnam.
Reso I_CNF::resolution(shared_ptr< Node > node, char v)
Resolution based on MulitiAnd node and variable v.
node v Reso, contain node Resolution and Subtitute Resolution
References isContain, Reso::resolution, mergeNode, Reso::subtituteSolution, getUniqueList.
Referenced by CNF::getDavidPutnam.
shared_ptr< Node > I_CNF::nodeToMultiAnd(shared_ptr< Node > node)
Convert node to MultiAnd, remove douplicate element and sort element This function are being used after generateCNF.
node - node to convert MultiAnd node, with deep of 3 Node::getLeaf, I_CNF::generateCNF
References getUniqueList.
Referenced by CNF::CNF.
shared_ptr< Node > I_CNF::generateCNF(shared_ptr< Node > originTree)
generate CNF form based on originTree, originTree will be changed, to prevent lost data, use deep copy of Node
originTree - Node pointer, origin tree to convert to CNF CNF tree Node::copy
References Tree::tree.
Referenced by CNF::CNF.
bool I_CNF::isUseless(shared_ptr< Node > node)
Check if node is useless.
node - MultiOr node True - if node is useless False - if node is not useless
Referenced by CNF::getDavidPutnam.
bool I_CNF::findJanus(shared_ptr< Node > node)
Check if Node contains Janus.
node - Node pointer to check for Janus True - If Janus found False - If Janus not found
Referenced by CNF::getDavidPutnam.
void I_CNF::getUniqueList(list< shared_ptr< Node > > &l)
get unique list of node
l - list of node contains douplicate member l - list of node contains unique member only
Referenced by resolution, nodeToMultiAnd.
bool I_CNF::isContain(shared_ptr< Node > nodes, string v)
check if node contain variable v
nodes - Node, node to check v - String, variable v True - if node contains variable v False - if node does not contains variable v
Referenced by resolution, mergeNode.
shared_ptr< Node > I_CNF::mergeNode(shared_ptr< Node > node1, shared_ptr< Node > node2, string v, string not_v)
merge two Node::variables list.
This function use for MultiOr, used by I_CNF::resolution node1 - first node node2 - second node v - string of variable v, upper case not_v - string of variable v, lowercase merged Node
References isContain.
Referenced by resolution.