SimpleTable
list< list< Rows > > SimpleTable::getAllRowsGroup()
References Tree::getListVariable, TruthTable::table.
Referenced by simplify.
list< Rows > SimpleTable::getQuineMcCluskey(list< list< Rows >> rowsGroup)
References Rows::setDontCare.
Referenced by simplify.
void SimpleTable::simplify()
References getAllRowsGroup, TruthTable::table, getQuineMcCluskey, TruthTable::hash.
Referenced by SimpleTable.
SimpleTable::SimpleTable(Tree root)
References simplify.
SimpleTable::SimpleTable(string prop="")
References simplify.
SimpleTable::SimpleTable(shared_ptr< Node > root)
References simplify.
SimpleTable::SimpleTable(TruthTable truthTable)
References simplify.