.TH "src/notation Directory Reference" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/notation Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBand\&.h\fP"
.br
.ti -1c
.RI "file \fBbiimplicate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbiimplicate\&.h\fP"
.br
.ti -1c
.RI "file \fBexists\&.cpp\fP"
.br
.ti -1c
.RI "file \fBexists\&.h\fP"
.br
.ti -1c
.RI "file \fBforall\&.cpp\fP"
.br
.ti -1c
.RI "file \fBforall\&.h\fP"
.br
.ti -1c
.RI "file \fBimplicate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimplicate\&.h\fP"
.br
.ti -1c
.RI "file \fBmultiand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmultiand\&.h\fP"
.br
.ti -1c
.RI "file \fBmultior\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmultior\&.h\fP"
.br
.ti -1c
.RI "file \fBnand\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnand\&.h\fP"
.br
.ti -1c
.RI "file \fBnegate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnegate\&.h\fP"
.br
.ti -1c
.RI "file \fBnode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnode\&.h\fP"
.br
.ti -1c
.RI "file \fBor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBor\&.h\fP"
.br
.ti -1c
.RI "file \fBstatement\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstatement\&.h\fP"
.br
.ti -1c
.RI "file \fBvalue\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvalue\&.h\fP"
.br
.ti -1c
.RI "file \fBvariable\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvariable\&.h\fP"
.br
.in -1c
