.TH "And" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
And
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <and\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnd\fP (shared_ptr< \fBNode\fP > l=nullptr, shared_ptr< \fBNode\fP > r=nullptr)"
.br
.ti -1c
.RI "\fB~And\fP () override"
.br
.ti -1c
.RI "bool \fBgetValue\fP (string valList) override"
.br
.RI "get proposition value "
.ti -1c
.RI "\fBRULES\fP \fBgetSTRuleName\fP (bool isNegation) override"
.br
.RI "get semantic taubleux rule name "
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBnandify\fP (bool isNegation) override"
.br
.RI "nandify proposition "
.ti -1c
.RI "void \fBgetSTNodeChild\fP (shared_ptr< \fBSTNode\fP > root, long pos, bool isNegation=false) override"
.br
.RI "get semantic taubleaux node child (\fBSTNode\&.left\fP and \fBSTNode\&.right\fP) "
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBcnfFilter\fP (bool isNegation=false) override"
.br
.RI "in this function node will be "
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBcnfDistribution\fP () override"
.br
.RI "cnf distribution - this function will be called after setVariable "
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBcopy\fP () override"
.br
.RI "deep copy node "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "And::And (shared_ptr< \fBNode\fP > l = \fCnullptr\fP, shared_ptr< \fBNode\fP > r = \fCnullptr\fP)\fC [explicit]\fP"

.SS "And::~And ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "shared_ptr< \fBNode\fP > And::cnfDistribution ()\fC [override]\fP, \fC [virtual]\fP"

.PP
cnf distribution - this function will be called after setVariable 
.PP
\fBReturns:\fP
.RS 4
node that applied distribution rule 
.RE
.PP

.PP
Reimplemented from \fBNode\fP\&.
.SS "shared_ptr< \fBNode\fP > And::cnfFilter (bool isNegation = \fCfalse\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
in this function node will be 
.IP "\(bu" 2
Remove bi-implicate
.IP "\(bu" 2
Remove implicate
.IP "\(bu" 2
Doing the morgan 
.PP
\fBParameters:\fP
.RS 4
\fIisNegation\fP - check if this node parent is Negation 
.RE
.PP
\fBReturns:\fP
.RS 4
node has been cnf filtered 
.RE
.PP

.PP

.PP
Reimplemented from \fBNode\fP\&.
.SS "shared_ptr< \fBNode\fP > And::copy ()\fC [override]\fP, \fC [virtual]\fP"

.PP
deep copy node 
.PP
\fBReturns:\fP
.RS 4
a deep copy of node 
.RE
.PP

.PP
Reimplemented from \fBNode\fP\&.
.SS "void And::getSTNodeChild (shared_ptr< \fBSTNode\fP > root, long pos, bool isNegation = \fCfalse\fP)\fC [override]\fP, \fC [virtual]\fP"

.PP
get semantic taubleaux node child (\fBSTNode\&.left\fP and \fBSTNode\&.right\fP) 
.PP
\fBParameters:\fP
.RS 4
\fIroot\fP - \fBSTNode\fP 
.br
\fIroot\fP - \fBSTNode\fP contains child 
.br
\fIpos\fP - position of child \fBNode\fP of \fBSTNode::nodes\fP list 
.br
\fIisNegation\fP - check if this node parent is Negation 
.RE
.PP

.PP
Reimplemented from \fBNode\fP\&.
.SS "\fBRULES\fP And::getSTRuleName (bool isNegation)\fC [override]\fP, \fC [virtual]\fP"

.PP
get semantic taubleux rule name 
.PP
\fBParameters:\fP
.RS 4
\fIisNegation\fP - check if this node parent is Negation 
.RE
.PP
\fBReturns:\fP
.RS 4
RULES - semantic taubleaux rule name 
.RE
.PP

.PP
Reimplemented from \fBNode\fP\&.
.SS "bool And::getValue (string valList)\fC [override]\fP, \fC [virtual]\fP"

.PP
get proposition value 
.PP
\fBParameters:\fP
.RS 4
\fIvalList\fP - string contains proposition variable and their value\&. 
.br
 e\&.g\&. 'A1B0C1' 
.RE
.PP
\fBReturns:\fP
.RS 4
proposition value 
.RE
.PP

.PP
Reimplemented from \fBNode\fP\&.
.SS "shared_ptr< \fBNode\fP > And::nandify (bool isNegation)\fC [override]\fP, \fC [virtual]\fP"

.PP
nandify proposition 
.PP
\fBParameters:\fP
.RS 4
\fIisNegation\fP - check if this node parent is Negation 
.RE
.PP
\fBReturns:\fP
.RS 4
nandified tree 
.RE
.PP

.PP
Reimplemented from \fBNode\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
