.TH "src/cnf/cnf.h" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cnf/cnf.h \- Conjunction normal form solver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./notation/multiand\&.h'\fP
.br
\fC#include '\&.\&./proposition/tree\&.h'\fP
.br
\fC#include '\&.\&./src/logging\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBReso\fP"
.br
.RI "The \fBReso\fP struct\&. "
.ti -1c
.RI "struct \fBI_CNF\fP"
.br
.RI "The Public interface of \fBCNF\fP\&. "
.ti -1c
.RI "class \fBCNF\fP"
.br
.RI "The \fBCNF\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Conjunction normal form solver\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
