.TH "src/cnf/cnf.cpp" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cnf/cnf.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include 'cnf\&.h'\fP
.br
\fC#include '\&.\&./utils\&.h'\fP
.br
\fC#include '\&.\&./notation/multior\&.h'\fP
.br
\fC#include '\&.\&./notation/negate\&.h'\fP
.br
\fC#include '\&.\&./notation/variable\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
