.TH "src/SemanticTableaux/enum.h" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SemanticTableaux/enum.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRULES\fP { \fBALPHA\fP =1, \fBDELTA\fP =2, \fBBETA\fP =3, \fBGAMMA\fP =4, \fBNN\fP =5, \fBALPHA\fP, \fBBETA\fP, \fBGAMMA\fP, \fBDELTA\fP, \fBNAN\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRULES\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIALPHA \fP\fP
.TP
\fB\fIDELTA \fP\fP
.TP
\fB\fIBETA \fP\fP
.TP
\fB\fIGAMMA \fP\fP
.TP
\fB\fINN \fP\fP
.TP
\fB\fIALPHA \fP\fP
.TP
\fB\fIBETA \fP\fP
.TP
\fB\fIGAMMA \fP\fP
.TP
\fB\fIDELTA \fP\fP
.TP
\fB\fINAN \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
