.TH "src/logging.cpp" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/logging.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'logging\&.h'\fP
.br
\fC#include <sys/time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBNowTime\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string NowTime ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
