.TH "MultiAndNorm" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiAndNorm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiand\&.h>\fP
.PP
Inherits \fBMultiAnd\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiAndNorm\fP (list< shared_ptr< \fBNode\fP > > listNodes=list< shared_ptr< \fBNode\fP > >())"
.br
.ti -1c
.RI "\fB~MultiAndNorm\fP () override"
.br
.ti -1c
.RI "string \fBtoString\fP () override"
.br
.RI "get proposition infix formular "
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBcopy\fP () override"
.br
.RI "deep copy node "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MultiAndNorm::MultiAndNorm (list< shared_ptr< \fBNode\fP > > listNodes = \fClist<shared_ptr<\fBNode\fP> >()\fP)\fC [explicit]\fP"

.SS "MultiAndNorm::~MultiAndNorm ()\fC [override]\fP"

.SH "Member Function Documentation"
.PP 
.SS "shared_ptr< \fBNode\fP > MultiAndNorm::copy ()\fC [override]\fP, \fC [virtual]\fP"

.PP
deep copy node 
.PP
\fBReturns:\fP
.RS 4
a deep copy of node 
.RE
.PP

.PP
Reimplemented from \fBMultiAnd\fP\&.
.SS "string MultiAndNorm::toString ()\fC [override]\fP, \fC [virtual]\fP"

.PP
get proposition infix formular 
.PP
\fBReturns:\fP
.RS 4
string of infix proposition 
.RE
.PP

.PP
Reimplemented from \fBMultiAnd\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
