.TH "src/notation/node.h" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/notation/node.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <array>\fP
.br
\fC#include '\&.\&./proposition/tableaux/enum\&.h'\fP
.br
\fC#include '\&.\&./proposition/tableaux/stnode\&.h'\fP
.br
\fC#include '\&.\&./utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
