.TH "Reso" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reso \- The \fBReso\fP struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cnf\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBresolution\fP = make_shared<\fBMultiAnd\fP>()"
.br
.RI "resolution "
.ti -1c
.RI "shared_ptr< \fBNode\fP > \fBsubtituteSolution\fP = make_shared<\fBMultiAnd\fP>()"
.br
.RI "subtitute resolution "
.in -1c
.SH "Detailed Description"
.PP 
The \fBReso\fP struct\&. 

Contain resolution and SubtituteResolution 
.SH "Member Data Documentation"
.PP 
.SS "shared_ptr<\fBNode\fP> Reso::resolution = make_shared<\fBMultiAnd\fP>()"

.PP
resolution 
.SS "shared_ptr<\fBNode\fP> Reso::subtituteSolution = make_shared<\fBMultiAnd\fP>()"

.PP
subtitute resolution 

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
