.TH "src/proposition/tableaux/semantictableaux.cpp" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/proposition/tableaux/semantictableaux.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'semantictableaux\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./notation/negate\&.h'\fP
.br
\fC#include 'enum\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
