.TH "src/table/simpletable.cpp" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/table/simpletable.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'simpletable\&.h'\fP
.br
\fC#include '\&.\&./utils\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
