.TH "src/proposition/tree.h" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/proposition/tree.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./notation/node\&.h'\fP
.br
\fC#include 'tableaux/stnode\&.h'\fP
.br
\fC#include 'tableaux/semantictableaux\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTree\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
