.TH "src/table/truthtable.cpp" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/table/truthtable.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iomanip>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'truthtable\&.h'\fP
.br
\fC#include '\&.\&./notation/multior\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
