.TH "src/notation/value.h" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/notation/value.h
.SH SYNOPSIS
.br
.PP
\fC#include 'node\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBValue\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
