.TH "Variable_v" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Variable_v
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <variable\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QChar \fBvarName\fP"
.br
.ti -1c
.RI "QChar \fBvalue\fP = true"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QChar Variable_v::value = true"

.SS "QChar Variable_v::varName"


.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
