.TH "src/notation/variable.cpp" 3 "Sun Nov 24 2019" "Version 1.0" "Logic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/notation/variable.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'variable\&.h'\fP
.br
\fC#include 'nand\&.h'\fP
.br
\fC#include 'value\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Logic from the source code\&.
