utils.h
bool contains(list< T > &listOfElements, const T &element)
Referenced by CNF::getListVariable, Exists::getSTNodeChild, ForAll::getSTNodeChild, Predicate::getListVariable, Tree::getListVariable.
void listReplaceAt(list< shared_ptr< T > > &mainList, list< shared_ptr< T >> &tmpList, long pos)
Referenced by Or::getSTNodeChild.
void listReplaceAt(list< shared_ptr< T > > &mainList, shared_ptr< T > tmpElem, long pos)
T readList(list< T > l1, uint pos)
Referenced by CNF::getDavidPutnam.
static bool isContain(string mainStr, string containedStr)
static bool isContain(string mainStr, char containedChar)
static bool isContain(string mainStr, list< char > containedChar)
static string getUniqueString(string str)