SemanticTableaux
bool SemanticTableaux::tautology
Referenced by isTautology, generateProof.
shared_ptr<STNode > SemanticTableaux::tableaux
Referenced by SemanticTableaux, ExportProof.
SemanticTableaux::SemanticTableaux(shared_ptr< Node > tree=nullptr)
References generateProof, tableaux.
SemanticTableaux::~SemanticTableaux()
bool SemanticTableaux::ExportProof(string title, string filenname)
References tableaux.
Referenced by Tree::exportProof.
bool SemanticTableaux::isTautology()
References tautology.
Referenced by Tree::isTautology.
void SemanticTableaux::generateProof(shared_ptr< STNode > root)
References NN, tautology.
Referenced by SemanticTableaux.