var annotated_dup =
[
    [ "And", "d0/dc9/class_and.html", "d0/dc9/class_and" ],
    [ "BiImplicate", "d5/da3/class_bi_implicate.html", "d5/da3/class_bi_implicate" ],
    [ "CNF", "dc/d0e/class_c_n_f.html", "dc/d0e/class_c_n_f" ],
    [ "Exists", "de/d16/class_exists.html", "de/d16/class_exists" ],
    [ "ForAll", "d8/dc5/class_for_all.html", "d8/dc5/class_for_all" ],
    [ "handler", "d1/df0/classhandler.html", "d1/df0/classhandler" ],
    [ "I_CNF", "d5/d80/struct_i___c_n_f.html", "d5/d80/struct_i___c_n_f" ],
    [ "Implicate", "de/d28/class_implicate.html", "de/d28/class_implicate" ],
    [ "logging", "d4/d8d/classlogging.html", "d4/d8d/classlogging" ],
    [ "MultiAnd", "d2/d2a/class_multi_and.html", "d2/d2a/class_multi_and" ],
    [ "MultiAndNorm", "d6/da5/class_multi_and_norm.html", "d6/da5/class_multi_and_norm" ],
    [ "MultiOr", "dd/d61/class_multi_or.html", "dd/d61/class_multi_or" ],
    [ "MultiOrNorm", "d6/d2d/class_multi_or_norm.html", "d6/d2d/class_multi_or_norm" ],
    [ "NAnd", "d9/d44/class_n_and.html", "d9/d44/class_n_and" ],
    [ "Negate", "df/d45/class_negate.html", "df/d45/class_negate" ],
    [ "Node", "dc/d8f/class_node.html", "dc/d8f/class_node" ],
    [ "Or", "d8/d1b/class_or.html", "d8/d1b/class_or" ],
    [ "Predicate", "d5/d30/class_predicate.html", "d5/d30/class_predicate" ],
    [ "Reso", "d1/dde/struct_reso.html", "d1/dde/struct_reso" ],
    [ "rootLogger", "d7/d88/structroot_logger.html", null ],
    [ "Rows", "d6/d54/class_rows.html", "d6/d54/class_rows" ],
    [ "SemanticTableaux", "d6/d22/class_semantic_tableaux.html", "d6/d22/class_semantic_tableaux" ],
    [ "SimpleTable", "d0/d52/class_simple_table.html", "d0/d52/class_simple_table" ],
    [ "Statement", "d7/da3/class_statement.html", "d7/da3/class_statement" ],
    [ "STNode", "d0/d75/class_s_t_node.html", "d0/d75/class_s_t_node" ],
    [ "Tree", "dd/df8/class_tree.html", "dd/df8/class_tree" ],
    [ "TruthTable", "dc/d49/class_truth_table.html", "dc/d49/class_truth_table" ],
    [ "Value", "d4/d72/class_value.html", "d4/d72/class_value" ],
    [ "Variable", "d2/d3c/class_variable.html", "d2/d3c/class_variable" ],
    [ "Variable_v", "de/d24/struct_variable__v.html", "de/d24/struct_variable__v" ]
];