CNF
CNF::CNF(shared_ptr< Node > otherTree)
CNF constructor, generate CNF of normal tree.
otherTree - tree to be convert to cnf form
References Tree::tree, I_CNF::generateCNF, I_CNF::nodeToMultiAnd.
CNF::CNF(string prop="")
CNF constructor, parse a CNF tree.
prop - proposition
References Tree::prop_in, Tree::tree, parse.
CNF::~CNF() override
string CNF::getDavidPutnam() override
get David Putnam
string, showing David Putnam result
References getListVariable, Tree::tree.
Referenced by getDavidPutnam.
list< string > CNF::getListVariable() override
References Tree::varList, Tree::prop_in, contains.
Referenced by getDavidPutnam.
shared_ptr< Node > CNF::parse(string prop)
parse cnf proposition
prop - cnf string of proposition MultiAnd represent proposition
References getMultiOr.
Referenced by CNF.
shared_ptr< Node > CNF::getMultiOr(string prop)
get MultiOr base on proposition
prop - cnf string of proposition MultiOr represent proposition
Referenced by parse.
void CNF::getDavidPutnam(shared_ptr< Node > tree, uint pos, string &result)
get David Putnam, this function is used by a public function
tree - cnf tree pos - current variable position result - string, represent Devaid Putname result
References I_CNF::findJanus, INFO, readList, Tree::varList, getDavidPutnam, I_CNF::isUseless, I_CNF::solveNonJanus, I_CNF::resolution.